apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: demo-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: frontend
        image: demo-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PUBLIC_API_URL
          value: ""
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3000"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-frontend
  namespace: demo-hello
spec:
  selector:
    app: demo-frontend
  ports:
  - port: 3000
    targetPort: 3000
