apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- backend.yaml
- frontend.yaml
- nginx.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: demo-hello
    app.kubernetes.io/version: v1.0.0
